name = "KevjaTestQuackle"
uuid = "96f3e403-9300-4b9f-922b-637d8320b081"
authors = ["Kaiwen Zhu <zhukaiwen113000@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
